version: "3.9"


services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_desafio
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: queries_challenge
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - .:/usr/db
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
